Allow multiple IDs
wiscostret/fplscrapR pull request #16
Opened 2020-07-27 18:15 UTC by eivindhammers

Allow for multiple entry IDs, as is implied by the description of "entryid" in docs ("The entry ID(s)."). Also removed the line requesting round info, which doesn't seem to be used.

2020-07-27 19:10 UTC, eivindhammers commented
I also added a function to retrieve captains (for multiple entries/GWs). Feel free to drop that from the pull request if it is of limited interest.

2020-07-28 10:56 UTC, wiscostret requested changes
Many thanks for this - this is all good ideas. If you want, you can separate the captains commit out in a separate pull request - I am happy to approve this with the requested changes. I am more in doubt about the other commit (allowing multiple entry IDs), but I will comment in detail on that.

2020-07-28 10:56 UTC, wiscostret commented on R/entry_functions.R
> +get_entry_captain <- function(entryid = NULL, gw = NULL, player_names = FALSE){
I would remove and default the player_names functionality - it´s a nice touch, and should be useful in the vast majority of cases; the get_player_name() function is light enough that this should not add too much to the load.
```suggestion
get_entry_captain <- function(entryid = NULL, gw = NULL){
```

2020-07-28 10:56 UTC, wiscostret commented on R/entry_functions.R
> +  if (player_names == TRUE) {
Cf. above, remove the if() statement here.
```suggestion
```

2020-07-28 10:56 UTC, wiscostret commented on R/entry_functions.R
> +  }
Cf. above, remove the if() statement wrapper here.

Would also add a reordering here to sort the return by entry and event
```suggestion
captain3 <- captain3[order(captain3$entry,captain3$event),]
```

2020-07-28 10:56 UTC, wiscostret commented on R/entry_functions.R
> +    names(captain3) <- c("captain_id", "captain_name", "entry", "event")
Renaming these to fit with package norms, allowing for easier merges with other function results.
```suggestion
    names(captain3) <- c("id", "playername", "entry", "event")
```

2020-07-28 11:02 UTC, wiscostret reviewed
Thanks for this also. Good spot on the roundinfo, not sure how that´s ended up there, poor quality checking on my part.

On adding functionality for multiple entry IDs, I´ve considered this a lot before. I shared some thoughts in a prior issue [here](https://github.com/wiscostret/fplscrapR/issues/15). The get_entry_picks() function returns a list of lists (and actually, in part, a list of list of lists), because of how the FPL API is (unhelpfully) structured. Adding multiple IDs with the suggested changes returns another list layer, so effectively you get a list of list of list of lists (phew). This is not a user-friendly data structure to work with, which is why I´ve preferred not to add this option, but I´m very open to further considerations.

As I mentioned on the issue, an alternative would be to add more specifically targeted functions, like a get_entry_player_picks() which would return only the $picks dataframe (which is what most users are looking for). This would be easier to add a multiple entry ID functionality to. Any further comments welcome.

2020-07-28 17:35 UTC, eivindhammers commented
Thanks for your feedback. The captains function is now in its own pull request, with suggested changes.

I second the idea of a `get_entry_player_picks()` function, returning a dataframe. The nested list returned by my function is something of a mess, yes.

2020-07-28 17:36 UTC, eivindhammers commented
I guess this PR can be closed. I might open a new one with a `get_entry_player_picks()` function.

2020-07-28 20:15 UTC, eivindhammers commented
Closing this PR, see #17 and #18.

2020-07-28 20:15 UTC, closed without merging